"""add ON DELETE behavior to every FK + index hot FK columns

Finding B (audit 2026-07-21): every ForeignKey in app/models.py was a bare FK
with no ondelete — hard-deleting a user or competitor was impossible (FK
violations from up to 9 child tables) and account deletion needed hand-written
cascade scripts. This migration recreates every FK constraint with the ON
DELETE behavior now declared in app/models.py:

    CASCADE  — all child rows (snapshots, change_events, reviews,
               review_snapshots, social_posts, job_postings, job_snapshots,
               battlecard_cache, campaigns -> competitors; competitors,
               campaigns, approved_actions, magic_link_tokens -> users;
               approved_actions -> change_events; action_plans -> campaigns;
               action_plan_items -> action_plans; geo_snapshots -> campaigns;
               app_pricing/app_tech -> apps; change_events -> snapshots, which
               are NOT NULL so SET NULL is impossible there)
    SET NULL — competitors.app_id -> apps (nullable discovery link)

The FK recreation is POSTGRES-ONLY (dialect-guarded), following the style of
revision 851bf9d63155: SQLite cannot ALTER constraints without a full
batch-mode table rebuild of 15 tables, dev SQLite DBs are disposable, and
SQLite does not enforce FKs in this app anyway (no PRAGMA foreign_keys=ON).
Fresh dev DBs get the ondelete behavior from app/models.py via create_all.

Constraint names are NOT hardcoded: prod constraints carry Postgres
autogenerated names (e.g. snapshots_competitor_id_fkey, or
fk_competitors_app_id which was explicitly named in 851bf9d63155), so each FK
is looked up by (constrained column, referred table) via the inspector and
recreated UNDER ITS EXISTING NAME. FKs already carrying the right ondelete are
skipped — the migration is idempotent / safe to re-run.

Finding C: Postgres does not auto-index FK columns; the dashboard's hottest
queries (app/routes/api_v1.py ~184-264) GROUP BY competitor_id with
MAX(fetched_at) / MAX(snapshot_at) per competitor. Composite/plain indexes are
created here (both dialects, IF NOT EXISTS) matching the declarations added to
app/models.py.

Revision ID: 012
Revises: 011
Create Date: 2026-07-23

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012'
down_revision: Union[str, None] = '011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Every FK in app/models.py: (table, column, referred_table, ondelete).
# All referred columns are the single-column primary key "id".
FK_RULES = [
    # children of users
    ("competitors", "user_id", "users", "CASCADE"),
    ("campaigns", "user_id", "users", "CASCADE"),
    ("approved_actions", "user_id", "users", "CASCADE"),
    ("magic_link_tokens", "user_id", "users", "CASCADE"),
    # children of competitors
    ("snapshots", "competitor_id", "competitors", "CASCADE"),
    ("change_events", "competitor_id", "competitors", "CASCADE"),
    ("reviews", "competitor_id", "competitors", "CASCADE"),
    ("review_snapshots", "competitor_id", "competitors", "CASCADE"),
    ("social_posts", "competitor_id", "competitors", "CASCADE"),
    ("job_postings", "competitor_id", "competitors", "CASCADE"),
    ("job_snapshots", "competitor_id", "competitors", "CASCADE"),
    ("battlecard_cache", "competitor_id", "competitors", "CASCADE"),
    ("campaigns", "competitor_id", "competitors", "CASCADE"),
    # children of snapshots (NOT NULL -> CASCADE, SET NULL impossible)
    ("change_events", "snapshot_before_id", "snapshots", "CASCADE"),
    ("change_events", "snapshot_after_id", "snapshots", "CASCADE"),
    # children of change_events
    ("approved_actions", "change_event_id", "change_events", "CASCADE"),
    # campaign tree
    ("action_plans", "campaign_id", "campaigns", "CASCADE"),
    ("action_plan_items", "plan_id", "action_plans", "CASCADE"),
    ("geo_snapshots", "campaign_id", "campaigns", "CASCADE"),
    # discovery / apps
    ("app_pricing", "app_id", "apps", "CASCADE"),
    ("app_tech", "app_id", "apps", "CASCADE"),
    # nullable discovery link on competitors
    ("competitors", "app_id", "apps", "SET NULL"),
]

# Hot FK indexes: (index_name, table, [columns]) — names match the
# index=True / Index() declarations in app/models.py so autogenerate stays clean.
INDEXES = [
    ("ix_competitors_user_id", "competitors", ["user_id"]),
    ("ix_snapshots_competitor_id_fetched_at", "snapshots", ["competitor_id", "fetched_at"]),
    ("ix_change_events_competitor_id_detected_at", "change_events", ["competitor_id", "detected_at"]),
    ("ix_reviews_competitor_id", "reviews", ["competitor_id"]),
    ("ix_review_snapshots_competitor_id_platform_snapshot_at", "review_snapshots",
     ["competitor_id", "platform", "snapshot_at"]),
    ("ix_social_posts_competitor_id", "social_posts", ["competitor_id"]),
    ("ix_job_postings_competitor_id", "job_postings", ["competitor_id"]),
    ("ix_job_snapshots_competitor_id", "job_snapshots", ["competitor_id"]),
    ("ix_magic_link_tokens_user_id", "magic_link_tokens", ["user_id"]),
    ("ix_approved_actions_user_id", "approved_actions", ["user_id"]),
    ("ix_approved_actions_change_event_id", "approved_actions", ["change_event_id"]),
    ("ix_campaigns_competitor_id", "campaigns", ["competitor_id"]),
]


def _set_fk_ondelete(target_ondelete_by_rule) -> None:
    """Drop + recreate each FK (Postgres only) with the desired ON DELETE,
    keeping its existing (autogenerated or explicit) constraint name."""
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return  # see module docstring: SQLite dev DBs rely on models.py/create_all
    inspector = sa.inspect(bind)
    # Snapshot all FK metadata up front so drops don't confuse later lookups.
    fks_by_table = {
        table: inspector.get_foreign_keys(table)
        for table in {rule[0] for rule in FK_RULES}
        if inspector.has_table(table)
    }
    for table, column, ref_table, _ in FK_RULES:
        desired = target_ondelete_by_rule((table, column, ref_table))
        for fk in fks_by_table.get(table, []):
            if fk["constrained_columns"] == [column] and fk["referred_table"] == ref_table:
                current = ((fk.get("options") or {}).get("ondelete") or "NO ACTION").upper()
                if current == (desired or "NO ACTION").upper():
                    break  # already correct — idempotent skip
                op.drop_constraint(fk["name"], table, type_="foreignkey")
                op.create_foreign_key(
                    fk["name"], table, ref_table,
                    [column], fk["referred_columns"] or ["id"],
                    ondelete=desired,
                )
                break
        else:
            # FK constraint missing entirely (should not happen on a migrated
            # DB) — create it so the schema converges on models.py.
            op.create_foreign_key(
                f"fk_{table}_{column}", table, ref_table, [column], ["id"],
                ondelete=desired,
            )


def upgrade() -> None:
    rules = {(t, c, r): od for t, c, r, od in FK_RULES}
    _set_fk_ondelete(lambda key: rules[key])

    # Finding C — hot FK indexes (both dialects, idempotent).
    for name, table, columns in INDEXES:
        op.create_index(name, table, columns, unique=False, if_not_exists=True)


def downgrade() -> None:
    for name, table, _ in reversed(INDEXES):
        op.drop_index(name, table_name=table, if_exists=True)
    # Restore bare FKs (no ON DELETE clause) on Postgres.
    _set_fk_ondelete(lambda key: None)
